import prisma from '../db/prisma';

type CodeSeed = { packageName: string; name: string; description: string; source: string };
type AqlSeed = { packageName: string; name: string; description: string; query: string; parameters?: Record<string, unknown> };

const codeFunctions: CodeSeed[] = [
  { packageName: 'patientTools', name: 'displayName', description: 'Creates a display name from a patient record.', source: 'export function displayName(params) { return [params.title, params.givenName, params.familyName].filter(Boolean).join(" "); }' },
  { packageName: 'patientTools', name: 'ageAt', description: 'Calculates age in full years at an ISO date.', source: 'export function ageAt(params) { const birth = new Date(params.birthDate); const at = new Date(params.at || Date.now()); let age = at.getUTCFullYear() - birth.getUTCFullYear(); const beforeBirthday = at.getUTCMonth() < birth.getUTCMonth() || (at.getUTCMonth() === birth.getUTCMonth() && at.getUTCDate() < birth.getUTCDate()); return Number.isFinite(age) ? age - (beforeBirthday ? 1 : 0) : null; }' },
  { packageName: 'patientTools', name: 'contactSummary', description: 'Formats available address and contact fields.', source: 'export function contactSummary(params) { return [params.street, [params.postalCode, params.city].filter(Boolean).join(" "), params.phone].filter(Boolean).join(" · "); }' },
  { packageName: 'labTools', name: 'latestByCode', description: 'Finds the most recent AQL row for a LOINC code.', source: 'export function latestByCode(params) { return (params.rows || []).filter((row) => row.loincCode === params.code).sort((a, b) => String(b.recordedAt || "").localeCompare(String(a.recordedAt || "")))[0] || null; }' },
  { packageName: 'labTools', name: 'formatQuantity', description: 'Formats magnitude and unit consistently.', source: 'export function formatQuantity(params) { return params.magnitude == null ? "" : `${params.magnitude}${params.unit ? ` ${params.unit}` : ""}`; }' },
  { packageName: 'labTools', name: 'isOutOfRange', description: 'Checks a numeric value against optional reference bounds.', source: 'export function isOutOfRange(params) { return (params.low != null && params.value < params.low) || (params.high != null && params.value > params.high); }' },
  { packageName: 'medicationTools', name: 'activeNames', description: 'Extracts medication names from result rows.', source: 'export function activeNames(params) { return [...new Set((params.rows || []).filter((row) => row.status !== "stopped").map((row) => row.medicationName).filter(Boolean))]; }' },
  { packageName: 'medicationTools', name: 'hasIngredient', description: 'Checks medication rows for an ingredient substring.', source: 'export function hasIngredient(params) { const needle = String(params.ingredient || "").toLowerCase(); return (params.rows || []).some((row) => String(row.medicationName || row.ingredient || "").toLowerCase().includes(needle)); }' },
  { packageName: 'medicationTools', name: 'summary', description: 'Builds a human-readable medication summary.', source: 'export function summary(params) { return [params.medicationName, params.dose, params.route, params.frequency].filter(Boolean).join(" · "); }' },
];

const templateQuery = (templateId: string, entryType: string) => `SELECT c/uid/value AS compositionUid, c/context/start_time/value AS recordedAt, c/composer/name AS composer, ${entryType}/name/value AS entryName, ${entryType}/archetype_node_id AS archetypeId FROM EHR ehr[ehr_id/value = :ehrId] CONTAINS COMPOSITION c CONTAINS ${entryType} WHERE c/archetype_details/template_id/value = '${templateId}' ORDER BY c/context/start_time/value DESC LIMIT 25`;
const aqlFunctions: AqlSeed[] = [
  { packageName: 'clinicalOverview', name: 'compositionTimeline', description: 'Recent compositions with template, time, composer and identifier.', query: "SELECT c/uid/value AS compositionUid, c/name/value AS compositionName, c/archetype_details/template_id/value AS templateId, c/context/start_time/value AS recordedAt, c/composer/name AS composer FROM EHR ehr[ehr_id/value = :ehrId] CONTAINS COMPOSITION c ORDER BY c/context/start_time/value DESC LIMIT 50" },
  { packageName: 'clinicalOverview', name: 'diagnosisHistory', description: 'Diagnosis compositions with diagnosis entry metadata.', query: templateQuery('vg_Diagnosis.v1.1.1', 'EVALUATION d').replaceAll('EVALUATION d/name', 'd/name').replaceAll('EVALUATION d/archetype_node_id', 'd/archetype_node_id') },
  { packageName: 'clinicalOverview', name: 'procedureHistory', description: 'Procedures with execution metadata.', query: templateQuery('vg_Procedure.v1.1.0', 'ACTION p').replaceAll('ACTION p/name', 'p/name').replaceAll('ACTION p/archetype_node_id', 'p/archetype_node_id') },
  { packageName: 'clinicalOverview', name: 'serviceRequests', description: 'Service requests with instruction metadata.', query: templateQuery('vg_ServiceRequest.v1.1.1', 'INSTRUCTION i').replaceAll('INSTRUCTION i/name', 'i/name').replaceAll('INSTRUCTION i/archetype_node_id', 'i/archetype_node_id') },
  { packageName: 'laboratory', name: 'labReportTimeline', description: 'Laboratory report compositions and observation metadata.', query: templateQuery('vg_DiagnosticReportLab.v1.1.2', 'OBSERVATION o').replaceAll('OBSERVATION o/name', 'o/name').replaceAll('OBSERVATION o/archetype_node_id', 'o/archetype_node_id') },
  { packageName: 'laboratory', name: 'analyteResults', description: 'Multi-column analyte values including LOINC code, magnitude and unit.', query: "SELECT c/uid/value AS compositionUid, c/context/start_time/value AS recordedAt, a/items[at0001]/value/value AS analyteName, a/items[at0001]/value/defining_code/code_string AS loincCode, a/items[at0024]/value/magnitude AS magnitude, a/items[at0024]/value/units AS unit FROM EHR ehr[ehr_id/value = :ehrId] CONTAINS COMPOSITION c CONTAINS OBSERVATION o[openEHR-EHR-OBSERVATION.laboratory_test_result.v1] CONTAINS CLUSTER a[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1] ORDER BY c/context/start_time/value DESC LIMIT 100" },
  { packageName: 'laboratory', name: 'specimenHistory', description: 'Specimen actions with composition context.', query: templateQuery('vg_Specimen.v1.0.0', 'ACTION s').replaceAll('ACTION s/name', 's/name').replaceAll('ACTION s/archetype_node_id', 's/archetype_node_id') },
  { packageName: 'medications', name: 'medicationStatements', description: 'Medication statements with evaluation metadata.', query: templateQuery('vg_MedicationStatement.v1.1.0', 'EVALUATION m').replaceAll('EVALUATION m/name', 'm/name').replaceAll('EVALUATION m/archetype_node_id', 'm/archetype_node_id') },
  { packageName: 'medications', name: 'administrationHistory', description: 'Medication administrations with action metadata.', query: templateQuery('vg_MedicationAdministration.v1.0.2', 'ACTION a').replaceAll('ACTION a/name', 'a/name').replaceAll('ACTION a/archetype_node_id', 'a/archetype_node_id') },
  { packageName: 'demographics', name: 'personCompositions', description: 'Person compositions with admin-entry metadata.', query: templateQuery('vg_Person.v1.1.1', 'ADMIN_ENTRY p').replaceAll('ADMIN_ENTRY p/name', 'p/name').replaceAll('ADMIN_ENTRY p/archetype_node_id', 'p/archetype_node_id') },
];

/** Idempotently installs the small, documented starter library. */
export async function ensureDefaultFunctionLibrary(): Promise<void> {
  await Promise.all(codeFunctions.map((item) => prisma.codeFunction.upsert({ where: { packageName_name: { packageName: item.packageName, name: item.name } }, create: item, update: {} })));
  await Promise.all(aqlFunctions.map((item) => prisma.aqlFunction.upsert({ where: { packageName_name: { packageName: item.packageName, name: item.name } }, create: { ...item, parameters: (item.parameters || {}) as any, autoload: false, enabled: true }, update: {} })));
}
