import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useDocumentTitle } from '../hooks/useDocumentTitle';
import { API_BASE_URL } from '../integration/apiBaseUrl';

type User = { id: string; username?: string; displayName?: string; email?: string; status: 'active' | 'inactive'; roles: ('USER' | 'ADMIN')[] };
const api = `${API_BASE_URL}/admin/users`;

export default function UsersAdmin() {
  useDocumentTitle('Users');
  const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [draft, setDraft] = useState({ username: '', displayName: '', email: '', password: '', role: 'USER' as 'USER' | 'ADMIN' });
  const load = useCallback(async () => { const response = await fetch(api, { credentials: 'include' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Users could not be loaded'); setUsers(data.users || []); }, []);
  useEffect(() => { void load().catch((reason: Error) => setError(reason.message)); }, [load]);
  const create = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(api, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...draft, roles: [draft.role] }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'User could not be created'); setDraft({ username: '', displayName: '', email: '', password: '', role: 'USER' }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'User could not be created'); } finally { setBusy(false); } };
  const update = async (id: string, body: Record<string, unknown>) => { setError(''); try { const response = await fetch(`${api}/${id}`, { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'User could not be updated'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'User could not be updated'); } };
  const action = async (id: string, path: string, body?: Record<string, unknown>) => { setError(''); try { const response = await fetch(`${api}/${id}/${path}`, { method: 'POST', credentials: 'include', headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); if (!response.ok) { const data = await response.json(); throw new Error(data.error || 'Action failed'); } await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Action failed'); } };
  return <div style={{ maxWidth: 1000, margin: '0 auto' }}><h1 style={{ marginTop: 0 }}>User management</h1><p style={{ color: 'var(--text-muted)' }}>Local Forms accounts, roles and server-side sessions.</p>{error && <p style={{ color: 'var(--danger-hover)' }}>{error}</p>}
    <form className="card" onSubmit={create} style={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: '1rem', marginBottom: '1.5rem' }}><h3 style={{ gridColumn: '1 / -1', margin: 0 }}>Create user</h3><input className="form-input" placeholder="Username" required value={draft.username} onChange={(event) => setDraft({ ...draft, username: event.target.value })} /><input className="form-input" placeholder="Display name" value={draft.displayName} onChange={(event) => setDraft({ ...draft, displayName: event.target.value })} /><input className="form-input" type="email" placeholder="Email (optional)" value={draft.email} onChange={(event) => setDraft({ ...draft, email: event.target.value })} /><input className="form-input" type="password" minLength={12} placeholder="Password (min. 12 characters)" required value={draft.password} onChange={(event) => setDraft({ ...draft, password: event.target.value })} /><select className="form-input" value={draft.role} onChange={(event) => setDraft({ ...draft, role: event.target.value as 'USER' | 'ADMIN' })}><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select><button className="btn" disabled={busy} type="submit">{busy ? 'Creating…' : 'Create user'}</button></form>
    <div className="card"><h3 style={{ marginTop: 0 }}>Users</h3><div style={{ display: 'grid', gap: '.75rem' }}>{users.map((user) => <section key={user.id} style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: '1rem', borderBottom: '1px solid var(--border)', paddingBottom: '.75rem' }}><div><strong>{user.displayName || user.username || 'External user'}</strong><div style={{ color: 'var(--text-muted)', fontSize: '.9rem' }}>{user.username || 'External identity'} · {user.email || 'No email'} · {user.status}</div><div style={{ display: 'flex', gap: '.5rem', marginTop: '.5rem' }}><select className="form-input" style={{ width: 110 }} value={user.roles.includes('ADMIN') ? 'ADMIN' : 'USER'} onChange={(event) => void update(user.id, { roles: [event.target.value] })}><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select><button className="btn secondary" onClick={() => void action(user.id, user.status === 'active' ? 'deactivate' : 'activate')}>{user.status === 'active' ? 'Deactivate' : 'Activate'}</button></div></div><div style={{ display: 'flex', flexDirection: 'column', gap: '.5rem' }}><button className="btn secondary" onClick={() => { const password = window.prompt('New password (at least 12 characters)'); if (password) void action(user.id, 'reset-password', { password }); }}>Reset password</button><button className="btn secondary" onClick={() => void action(user.id, 'revoke-sessions')}>Revoke sessions</button></div></section>)}</div></div></div>;
}
